const sampleData = [
  {
    id: 1,
    thumbnail: 'https://place-hold.it/300x300',
    name: 'Lava episode 1',
    type: 'mp4 file',
    size: '10mb',
    url: 'https://www.youtube.com/watch?v=07d2dXHYb94',
    description: 'description',
  },
  {
    id: 2,
    thumbnail: 'https://place-hold.it/300x300',
    name: 'Lava episode 2',
    type: 'mp4 file',
    size: '10mb',
    url: 'https://www.youtube.com/watch?v=07d2dXHYb94',
    description: 'description',
  },
  {
    id: 3,
    thumbnail: 'https://place-hold.it/300x300',
    name: 'Lava episode 3',
    type: 'mp4 file',
    size: '10mb',
    url: 'https://www.youtube.com/watch?v=07d2dXHYb94',
    description: 'description',
  },
  {
    id: 4,
    thumbnail: 'https://place-hold.it/300x300',
    name: 'Lava episode 4',
    type: 'mp4 file',
    size: '10mb',
    url: 'https://www.youtube.com/watch?v=07d2dXHYb94',
    description: 'description',
  },
  {
    id: 5,
    thumbnail: 'https://place-hold.it/300x300',
    name: 'Lava episode 5',
    type: 'mp4 file',
    size: '10mb',
    url: 'https://www.youtube.com/watch?v=07d2dXHYb94',
    description: 'description',
  },
  {
    id: 6,
    thumbnail: 'https://place-hold.it/300x300',
    name: 'Lava episode 6',
    type: 'mp4 file',
    size: '10mb',
    url: 'https://www.youtube.com/watch?v=07d2dXHYb94',
    description: 'description',
  },
  {
    id: 7,
    thumbnail: 'https://place-hold.it/300x300',
    name: 'Lava episode 7',
    type: 'mp4 file',
    size: '10mb',
    url: 'https://www.youtube.com/watch?v=07d2dXHYb94',
    description: 'description',
  },
  {
    id: 8,
    thumbnail: 'https://place-hold.it/300x300',
    name: 'Lava episode 8',
    type: 'mp4 file',
    size: '10mb',
    url: 'https://www.youtube.com/watch?v=07d2dXHYb94',
    description: 'description',
  },
  {
    id: 9,
    thumbnail: 'https://place-hold.it/300x300',
    name: 'Lava episode 9',
    type: 'mp4 file',
    size: '10mb',
    url: 'https://www.youtube.com/watch?v=07d2dXHYb94',
    description: 'description',
  },
  {
    id: 10,
    thumbnail: 'https://place-hold.it/300x300',
    name: 'Lava episode 10',
    type: 'mp4 file',
    size: '10mb',
    url: 'https://www.youtube.com/watch?v=07d2dXHYb94',
    description: 'description',
  },
  {
    id: 11,
    thumbnail: 'https://place-hold.it/300x300',
    name: 'Lava episode 11',
    type: 'mp4 file',
    size: '10mb',
    url: 'https://www.youtube.com/watch?v=07d2dXHYb94',
    description: 'description',
  },
  {
    id: 12,
    thumbnail: 'https://place-hold.it/300x300',
    name: 'Lava episode 12',
    type: 'mp4 file',
    size: '10mb',
    url: 'https://www.youtube.com/watch?v=07d2dXHYb94',
    description: 'description',
  },
];

export { sampleData };
