export const API_ENDPOINT = {
  login: 'user/signin',
  signup: 'user/signup',
  forgotPassword: 'user/resetPassword',
  resetPassword: 'user/newPassword',
  profile: 'user/current',
  video: 'video',
  usersList: 'user/list',
  upateProfile: 'user/update',
  changePassword: 'user/changePassword',
  assignVideo: 'video/assign',
  createVideo: 'video/add',
  editVideo: 'video/update',
  deleteVideo: 'video/delete',
  addSegment: 'video/addSegment',
  editSegment: 'video/editSegment',
  deleteSegment: 'video/deleteSegment',
};
